
var Calendar=Control.extend({'initialize':function(el,options){this.options={'variant':0,'blank':false,'format':'%Y-%m-%d','showHour':false,'showMinute':false,'showSecond':false,'showMeridiem':false,'minYear':new Date().getFullYear()-1,'maxYear':new Date().getFullYear()+3}
this.element=$(el);this.setOptions(options);this.__date=this.__import();this.__buildComponents();if(this.options.blank&&this.element.value==''){this.__draw();this.element.value='';}else{this.__draw();}
this.__bindEvents();},'hide':function(){this.components.dialog.hide();},'show':function(){this.components.dialog.show();},'__dayNames':['S','M','T','W','T','F','S'],'__dayStart':0,'__patterns':{'Y':'(\\d{4})','m':'(\\d{2})','d':'(\\d{2})','H':'(\\d{2})','i':'(\\d{2})','s':'(\\d{2})','j':'(\\d+)','g':'(\\d+)','n':'(\\d+)','k':'(\\d+)','z':'(\\d+)','a':'(\\[apm]+)','G':'(\\d+)','A':'(\\[APM]+)'},'__export':function(){this.__map={'j':new Number(this.__data['day']),'g':new Number(this.components.hourInput.value),'k':new Number(this.components.minuteInput.value),'z':new Number(this.components.secondInput.value),'a':this.components.meridianInput.value==1?'pm':'am'}
switch(this.options.variant){case 1:var t=this.components.monthYearInput.value.split('.');this.__map['Y']=new Number(t[0]);this.__map['n']=new Number(t[1])+1;break;default:this.__map['Y']=new Number(this.components.yearInput.value);this.__map['n']=new Number(this.components.monthInput.value)+1;break;}
this.__map['G']=(this.__map['a']=='am')?(this.__map['g']<12?this.__map['g']:0):(this.__map['g']<12?12+this.__map['g']:12);$extend(this.__map,{'d':(this.__map['j']<10?'0':'')+this.__map['j'],'m':(this.__map['n']<10?'0':'')+this.__map['n'],'H':(this.__map['G']<10?'0':'')+this.__map['G'],'h':(this.__map['g']<10?'0':'')+this.__map['g'],'i':(this.__map['k']<10?'0':'')+this.__map['k'],'s':(this.__map['z']<10?'0':'')+this.__map['z'],'A':this.__map['a'].toUpperCase()});var result=this.options.format;for(var i in this.__map){if(result.match('%'+i)){switch(i){case'H':case'h':this.options.showHour=true;break;case'i':case'k':this.options.showMinute=true;break;case's':case'z':this.options.showSecond=true;break;case'a':case'A':this.options.showMeridiem=true;break;}
result=result.replace('%'+i,this.__map[i]);}}
this.element.value=result;if(this.element.onchange){this.element.onchange(this.element);}},'__monthYearInputChange':function(){var t=this.components.monthYearInput.value.split('.');this.__data['year']=t[0];this.__data['month']=t[1];this.__draw();},'__hourInputChange':function(){this.__data['hour']=this.components.hourInput.value;this.__draw();},'__minuteInputChange':function(){this.__data['minute']=this.components.minuteInput.value;this.__export();},'__secondInputChange':function(){this.__data['second']=this.components.secondInput.value;this.__export();},'__meridianInputChange':function(){this.__export();},'__buttonNextClick':function(){switch(this.options.variant){case 1:var t=this.components.monthYearInput.value.split('.');t[1]=parseInt(t[1])+1;if(t[1]>11){t[0]=parseInt(t[0])+1;t[1]=0;}
this.components.monthYearInput.value=t.join('.');this.components.monthYearInput.fireEvent('change');break;default:this.__monthWidget.up();if(this.__monthWidget.getValue()==0){this.__yearWidget.up();}
break;}},'__buttonPrevClick':function(){switch(this.options.variant){case 1:var t=this.components.monthYearInput.value.split('.');t[1]=parseInt(t[1])-1;if(t[1]<0){t[0]=parseInt(t[0])-1;t[1]=0;}
this.components.monthYearInput.value=t.join('.');this.components.monthYearInput.fireEvent('change');break;default:this.__monthWidget.down();if(this.__monthWidget.getValue()==11){this.__yearWidget.down();}
break;}},'__buttonTodayClick':function(){this.__setDefaultDate();this.__draw();},'__elementFocus':function(e){e=new Event(e);if(!this.components.dialog){this.components.dialog=new Dialog(this.components.container,{'title':' ','autoClose':true,'width':310,'onClose':function(){this.components.dialog=null;}.bind(this),'height':(window.gecko?290:310)});}
var pos=$(e.target).getPosition();this.components.dialog.moveTo(pos.y-5,pos.x-5);this.components.dialog.setTitle(this.humanDate(this.__data));this.element.blur();if(window.ie){this.__draw();}},'__buttonBlankClick':function(){this.element.value='';this.hide();},'__buttonCloseClick':function(){this.hide();},'__frameMouseDown':function(e){e=new Event(e);var parent=e.target;while(parent){if(parent.nodeName&&parent.nodeName.toLowerCase()=='td'){break;}
parent=parent.parentNode;}
if(parent&&parent.day){this.__todayTd.className='day';parent.className='today';this.__todayTd=parent;this.__data['day']=parent.day;this.__export();this.hide();}},'__bindEvents':function(){switch(this.options.variant){case 1:this.addListener(this.components.monthYearInput,'change',this.__monthYearInputChange);this.addListener(this.components.hourInput,'change',this.__hourInputChange);this.addListener(this.components.minuteInput,'change',this.__minuteInputChange);this.addListener(this.components.secondInput,'change',this.__secondInputChange);this.addListener(this.components.meridianInput,'change',this.__meridianInputChange);break;default:break;}
this.addListener(this.components.buttonNext,'click',this.__buttonNextClick);this.addListener(this.components.buttonPrev,'click',this.__buttonPrevClick);this.addListener(this.components.buttonToday,'click',this.__buttonTodayClick);this.addListener(this.components.buttonBlank,'click',this.__buttonBlankClick);this.addListener(this.element,'focus',this.__elementFocus);this.addListener(this.components.frame,'mousedown',this.__frameMouseDown);},'__buildComponents':function(){this.element.setProperty('readonly','readonly');this.components={'container':Widget.table({'class':'m-calendar'}),'date':Widget.div({'class':'date'}),'buttonPrev':Widget.div({'class':'m-control'},Widget.fromHTML('&laquo;')),'buttonNext':Widget.div({'class':'m-control'},Widget.fromHTML('&raquo;')),'buttonBlank':Widget.button({'class':'m-form-button'},__('Clear')),'buttonClose':Widget.button({'class':'m-form-button m-button-close'},__('Close')),'buttonToday':Widget.button({'class':'m-form-button'},__('Today')),'frame':Widget.div({'class':'m-frame'}),'grid':Widget.table({'class':'grid'}),'buttons':Widget.div({'class':'buttons'})};switch(this.options.variant){case 1:$extend(this.components,{monthYearInput:Widget.select({'class':'m-form-input'}),hourInput:Widget.select({'class':'m-form-input'}),minuteInput:Widget.select({'class':'m-form-input'}),meridianInput:Widget.select({'class':'m-form-input'}),secondInput:Widget.select({'class':'m-form-input'})});break;default:$extend(this.components,{yearInput:Widget.input({'class':'m-form-input','size':4,'maxlength':4}),monthInput:Widget.input({'class':'m-form-input','size':3,'maxlength':3}),hourInput:Widget.input({'class':'m-form-input','size':2,'maxlength':2}),minuteInput:Widget.input({'class':'m-form-input','size':2,'maxlength':2}),meridianInput:Widget.input({'class':'m-form-input','size':2,'maxlength':2}),secondInput:Widget.input({'class':'m-form-input','size':2,'maxlength':2})});break;}
this.components.container.appendChildren([Widget.thead({'class':'head'},Widget.tr(null,function(){var els=[];els.push(Widget.td({style:{textAlign:'left',verticalAlign:'middle'}},this.components.buttonPrev));switch(this.options.variant){case 1:els.push(Widget.td({colspan:2,style:{textAlign:'center'}},this.components.monthYearInput));break;default:els.push(Widget.td({style:{textAlign:'center'}},this.components.monthInput));els.push(Widget.td({style:{textAlign:'center'}},this.components.yearInput));break;}
els.push(Widget.td({style:{textAlign:'right',verticalAlign:'middle'}},this.components.buttonNext));return els;}.bind(this).call())),Widget.tbody({'class':'body'},[Widget.tr({'class':'main',style:{textAlign:'center'}},Widget.td({colspan:4},this.components.frame)),Widget.tr({'class':'head'},[Widget.td(null,this.components.hourInput),Widget.td(null,this.components.minuteInput),Widget.td(null,this.components.secondInput),Widget.td(null,this.components.meridianInput)]),Widget.tr(null,[Widget.td({colspan:4,'style':'overflow: auto','class':'m-buttons'},[this.components.buttonBlank,this.components.buttonToday])])])]);switch(this.options.variant){case 1:for(var y=this.options.minYear;y<=this.options.maxYear;y++){for(var m=0;m<12;m++){this.components.monthYearInput.appendChild(Widget.option({value:y+'.'+m},this.__getMonthName(m).substr(0,3)+' '+y));}}
for(var i=0;i<60;i++){this.components.minuteInput.appendChild(Widget.option({value:i},i<10?'0'+i:i));this.components.secondInput.appendChild(Widget.option({value:i},i<10?'0'+i:i));}
for(var i=1;i<=12;i++){this.components.hourInput.appendChild(Widget.option({value:i},i<10?'0'+i:i));}
this.components.meridianInput.appendChildren([Widget.option({value:0},'AM'),Widget.option({value:1},'PM')]);break;default:this.__yearWidget=new SpinButton(this.components.yearInput,{'defaultValue':this.__data['year'],'minValue':this.options.minYear,'maxValue':this.options.maxYear,'step':1,'onChange':function(){this.__data['year']=this.components.yearInput.value;this.__draw();}.bindAsEventListener(this)});this.__monthWidget=new SpinButton(this.components.monthInput,{'values':[__('Jan'),__('Feb'),__('Mar'),__('Apr'),__('May').substr(0,3),__('Jun'),__('Jul'),__('Aug'),__('Sep'),__('Oct'),__('Nov'),__('Dec')],'cycle':true,'onChange':function(){this.__data['month']=this.components.monthInput.value;this.__draw();}.bindAsEventListener(this)});this.__hourWidget=new SpinButton(this.components.hourInput,{'minValue':1,'maxValue':12,'defaultValue':12,'values':function(){var hours=[];for(var i=1;i<=12;i++)
hours[i]=new String(i<10?'0'+i:i);return hours;}.call(),'cycle':true,'onChange':function(){this.__export()}.bind(this)});this.__minuteWidget=new SpinButton(this.components.minuteInput,{'values':function(){var m=[];for(var i=0;i<60;i++)
m[i]=new String(i<10?'0'+i:i);return m;}.call(),'cycle':true,'onChange':function(){this.__export()}.bind(this)});this.__secondWidget=new SpinButton(this.components.secondInput,{'values':function(){var m=[];for(var i=0;i<60;i++)
m[i]=new String(i<10?'0'+i:i);return m;}.call(),'cycle':true,'onChange':function(){this.__export()}.bind(this)});this.__meridianWidget=new SpinButton(this.components.meridianInput,{'values':['AM','PM'],'cycle':true,'defaultValue':0,'onChange':function(){this.__export();}.bind(this)});break;}
this.components.frame.appendChild(this.components.grid);},'__setDefaultDate':function(){var today=new Date();this.__data={};this.__data['year']=today.getFullYear();this.__data['month']=today.getMonth();this.__data['day']=today.getDate();this.__data['hour']=0;this.__data['minute']=0;this.__data['second']=0;if(this.__data['year']<this.options.minYear){this.__data['year']=this.options.minYear;}
if(this.__data['year']>this.options.maxYear){this.__data['year']=this.options.maxYear;}},'__import':function(){this.__data={};var value=this.element.value;if(!value){this.__setDefaultDate();}else{var pairs={};var pattern=this.options.format;for(var i in this.__patterns){pattern=pattern.replace('%'+i,this.__patterns[i]);}
var pattern=new RegExp(pattern);var value=pattern.exec(value);if(value){var format=this.options.format.match(/%[a-zA-Z]/g);for(var i=0;i<format.length;i++){if(typeof format[i]!='undefined'&&typeof format[i]==typeof value[i+1]){pairs[format[i].substr(1)]=new Number(value[i+1]);}else{return;}}
this.__data['year']=pairs['Y'];this.__data['month']=pairs['m']-1;this.__data['day']=pairs['d'];this.__data['hour']=pairs['H'];this.__data['minute']=pairs['i'];this.__data['second']=pairs['s'];}else{this.__setDefaultDate();}}},'__draw':function(){var cursor=new Date();cursor.setFullYear(this.__data['year']);cursor.setMonth(this.__data['month']);cursor.setDate(1);switch(this.options.variant){case 1:this.components.monthYearInput.value=parseInt(this.__data['year'])+'.'+parseInt(this.__data['month']);this.components.minuteInput.value=this.__data['minute'];this.components.secondInput.value=this.__data['second'];if(this.__data['hour']>=12){if(this.__data['hour']>12){this.components.hourInput.value=this.__data['hour']-12;}
this.components.meridianInput.value=1;}else{if(this.__data['hour']==0){this.components.hourInput.value=12;}
this.components.meridianInput.value=0;}
if(this.options.showHour==false){this.components.hourInput.hide();}
if(this.options.showMinute==false){this.components.minuteInput.hide();}
if(this.options.showSecond==false){this.components.secondInput.hide();}
if(this.options.showMeridiem==false){this.components.meridianInput.hide();}
break;default:this.__yearWidget.setValue(parseInt(this.__data['year']));this.__monthWidget.setValue(parseInt(this.__data['month']));if(this.__data['hour']>=12){if(this.__data['hour']>12){this.__hourWidget.setValue(this.__data['hour']-12);}
this.__meridianWidget.setValue(1);}else{if(this.__data['hour']==0){this.__hourWidget.setValue(12);}
this.__meridianWidget.setValue(0);}
this.__minuteWidget.setValue(this.__data['minute']);this.__secondWidget.setValue(this.__data['second']);if(this.options.showHour==false){this.__hourWidget.element.hide();}
if(this.options.showMinute==false){this.__minuteWidget.element.hide();}
if(this.options.showSecond==false){this.__secondWidget.element.hide();}
if(this.options.showMeridiem==false){this.__meridianWidget.element.hide();}
break;}
while(cursor.getDay()!=this.__dayStart){cursor.setTime(cursor.getTime()-3600*24*1000);}
if(!this.components.grid.__days){this.components.grid.__days=new Array();var tr=Widget.tr();var dstart=this.__dayStart;for(var i=0;i<7;i++){if($type(this.__dayNames[dstart])==false){dstart=0;}
var td=Widget.th(null,this.__dayNames[dstart]);dstart++;tr.appendChild(td);}
var thead=Widget.thead(null,tr);this.components.grid.appendChild(thead);var dnumber=new Number(1);var inmonth=false;var tbody=Widget.tbody();for(var j=0;j<6;j++){var tr=Widget.tr({'class':'days'});for(var i=0;i<7;i++){var td=Widget.td(null,'-');this.components.grid.__days.push(td);tr.appendChild(td);}
tbody.appendChild(tr);}
this.components.grid.appendChild(tbody);this.components.frame.appendChild(this.components.grid);}
var inmonth=false;for(var j=0;j<this.components.grid.__days.length;j++){var today=false;var day=this.components.grid.__days[j];var cur=cursor.getDate();if(cur==1){inmonth=!inmonth;}
if(inmonth){day.day=cur;if(cur==this.__data['day']){today=true;}}
day.className=(today?'today':(inmonth?'day':''));day.innerHTML=cur;if(day.className=='today'){this.__todayTd=day;}
cursor.setTime(cursor.getTime()+3600*24*1000);}
if(window.ie){var iesucks=Widget.div(null,this.components.grid);this.components.frame.innerHTML=iesucks.innerHTML;}
if(this.components.dialog){this.components.dialog.setTitle(this.humanDate(this.__data));}
this.__export();},'__getMonthName':function(monthNumber){switch(parseInt(monthNumber)){case 0:return __('January');break;case 1:return __('February');break;case 2:return __('March');break;case 3:return __('April');break;case 4:return __('May');break;case 5:return __('June');break;case 6:return __('July');break;case 7:return __('August');break;case 8:return __('September');break;case 9:return __('October');break;case 10:return __('November');break;case 11:return __('December');break;}},'humanDate':function(current){return this.__getMonthName(current['month'])+' '+current['day']+', '+current['year'];}});