
var Notebook=Control.extend({'history':[],'initialize':function(container,options){this.options={'selectEvent':'mousedown','forceUpdate':false,'allowBookmark':true,'autoSelect':true,'preloadContent':false,'removePageContent':false,'confirmClose':false}
this.history=[];this.element=$(container);this.setOptions(options);this.__buildComponents();},'__buildComponents':function(){this.components={element:Widget.div({'class':'m-notebook'}),tabs:Widget.ul({'class':'tabs'}),frame:Widget.table({'class':'frametable'}),contents:Widget.td({'class':'contents'}),page:Widget.div({'class':'page'})}
this.components.frame.appendChild(Widget.tbody(null,Widget.tr(null,this.components.contents)));this.components.contents.appendChild(this.components.page);this.components.element.appendChildren([this.components.tabs,this.components.frame]);this.element.appendChild(this.components.element);this.components.element.parent=this;this.__tabs={};this.__contents={};this.__bindEvents();this.components.element.style.width='100%';this.components.contents.style.height='100%';},'__bindEvents':function(){this.components.tabs.addEvent(this.options.selectEvent,function(e){var e=new Event(e);var obj=e.target;while(obj&&obj.nodeName.toLowerCase()!='li'){obj=obj.parentNode;}
if(obj&&obj.parent){obj.parent.selectPage(obj.name,false);if(obj.options&&obj.options.onSelect){obj.options.onSelect();}}});},'resizeTo':function(width,height){$(this.components.contents).style.overflow='auto';$(this.components.element).resizeTo(width,-1);$(this.components.contents).resizeTo(-1,height);if(window.ie){for(var i in this.__contents){$(this.__contents[i]).resizeTo(-1,height);}}},'selectPage':function(name,focus){if(this.__selected){caretHack(this.__contents[this.__selected]);}
focus=$type(focus)?focus:true;if(this.options.forceUpdate==true||this.__tabs[name].__firstViewed==null){this.__updateContent(name);}
if(this.options.removePageContent){for(var i in this.__tabs){this.__tabs[i].className='m-tab';}
if(this.__tabs[name].__firstViewed!=null){var scripts=this.__contents[name].getElementsByTagName('script');while(scripts.length){$(scripts[0]).remove();}}
this.components.page.setContent(this.__contents[name]);}else{for(var i in this.__tabs){this.__tabs[i].className='m-tab';this.__contents[i].hide();}}
this.__contents[name].show();this.__tabs[name].className='m-tab m-selected';this.__selected=name;if(this.options.allowBookmark){var y=Browser.pageScrollY();Browser.followMark(name);Browser.focusElement(this.element);}
if(this.history.length){var tail=this.history.pop();if(tail!=name){this.history.push(tail);}}
this.history.push(name);},'__initialCheck':function(){log('No bookmarked page found.');if(!this.__selected){for(var index in this.__tabs){this.selectPage(index);return;}}},'pageExists':function(id){return $type(this.__tabs[id]);},'renamePage':function(id,title){var tab=this.__tabs[id];tab.tabText.replaceChild(document.createTextNode(title),tab.tabText.firstChild);tab.tabTitle=title;if(tab.options.onRename){tab.options.onRename();}},'__isSelected':function(id){return this.__tabs[id].className.match(/m-selected/);},'__renameInputBlur':function(e,tab){this.renamePage(tab.name,tab.input.value);tab.tabText.show();tab.input.remove();tab.input=null;},'__renameInputKeydown':function(e,tab){var e=new Event(e);if(e.key.match(/^(enter|esc|tab)$/)){this.__renameInputBlur(e,tab);e.stop();}},'__renamePage':function(tab){if(!tab.input){if(this.__isSelected(tab.name)){var input=Widget.input({'class':'m-rename'});tab.tabText=$(tab.tabText);tab.tabText.parentNode.appendChild(input);tab.tabText.hide();input.value=tab.tabText.firstChild.nodeValue;input.addEvent('keydown',this.__renameInputKeydown.bindAsEventListener(this,tab));input.addEvent('blur',this.__renameInputBlur.bindAsEventListener(this,tab));this.addTimer(function(){this.select();this.focus();}.bind(input),100);tab.input=input;}}},'__createPage':function(name,content){var tab=Widget.li({'class':'m-tab'});tab.name=name.id;tab.tabTitle=name.title;tab.options=name.options;tab.tabText=Widget.fromHTML(name.title);tab.pageTitle=Widget.span({'class':'m-tab-label'},tab.tabText);tab.appendChild(Widget.span({'class':'m-tab-left'}));tab.appendChild(tab.pageTitle);tab.appendChild(Widget.span({'class':'m-tab-right'}));if(name.options.allowRename){tab.addEvent('mousedown',this.__renamePage.bind(this,tab));}
if(name.options.allowClose){var close=Widget.span({'class':'m-tab-close'},Widget.fromHTML('&times;'));close.addEvent('mousedown',function(e){e=new Event(e);if(this.parent.options.confirmClose){Dialog.question(__('Are you sure you want to close this tab?'),{'onYes':function(dialog){if(this.options.onClose){this.options.onClose();}
this.parent.closePage(this.name);dialog.close();}.bind(this)});}else{if(this.options.onClose){this.options.onClose();}
this.parent.closePage(this.name);}
e.stop();}.bindAsEventListener(tab));tab.appendChild(close);}
tab.parent=this;this.components.tabs.appendChild(tab);tab.__contentSource=content;this.__tabs[name.id]=tab;if($type(content)=='element'){var content=Widget.div({'class':'m-notebook-content','name':name.id},content);}else{var content=Widget.div({'class':'m-notebook-content','name':name.id});}
if(!this.options.removePageContent){this.components.page.appendChild(content);}
content.hide();this.__contents[name.id]=content;},'updatePage':function(name,content){if(typeof this.__tabs[name]!='undefined'){var tab=this.__tabs[name];if(content){tab.__contentSource=content;}
this.__updateContent(name);}},'cleanCache':function(){for(var name in this.__tabs){if(typeof(this.__tabs[name].__contentSource)=='object'){this.__tabs[name].__firstViewed=null;}}},'cleanPage':function(name,content){if(typeof this.__tabs[name]!='undefined'){var tab=this.__tabs[name];if(content){tab.__contentSource=content;}
this.__tabs[name].__firstViewed=null;}},'__updateContent':function(name){var content=this.__tabs[name].__contentSource;if(typeof(content)=='string'&&content.match(/^http:\/\//i)){this.__contents[name].setContent({'url':content});}else{this.__contents[name].setContent(content);}
if($type(content)=='element'){$(content).show();}
this.__tabs[name].__firstViewed=true;},'getObject':function(){return this.components.element;},'getContent':function(name){return this.__contents[name];},'closePage':function(name){if(this.__tabs[name]){this.__contents[name].dump();this.__tabs[name].dump();delete this.__tabs[name];delete this.__contents[name];this.history.pop();while(this.history.length){var p=this.history.pop();if(this.__tabs[p]){return this.selectPage(p);}}
for(var first in this.__tabs){return this.selectPage(first);}}},'injectBefore':function(what,name,content,options){var id=this.addPage(name,content,options);this.__tabs[id].injectBefore(this.__tabs[what]);},'injectAfter':function(what,name,content,options){var id=this.addPage(name,content,options);this.__tabs[id].injectAfter(this.__tabs[what]);},'setPageTitle':function(name,title){if(this.__tabs[name]){this.__tabs[name].pageTitle.setContent(Widget.fromHTML(title));}},'map':function(params){for(var i=0;i<params.length;i++){var param=params[i];var match=location.href.match(new RegExp('.*#('+param.id+')'));if(match){param.id=match[1];if(typeof param.url!='undefined'){var url=param['url'];url=url.replace('%match','%1');for(var i=2;i<match.length;i++){url=url.replace('%'+(i-1),match[i]);}
param.url=url;if(typeof param.rpc!='undefined'){new Ajax(param.url).rpc();}else{this.addPage(param,param,param);}}
if(typeof param.callback!='undefined'){param.callback(match);}}}},'addPage':function(name,content,options){if($type(name)=='string'){var temp=name;name={'id':name,'title':name};}
name.options=options||{};if(this.__tabs[name.id]){log('A tab with the same name already exists!');this.updatePage(name.id,content);}else{this.__createPage(name,content);if(this.options.preloadContent){this.__updateContent(name.id);}
if(!this.__selected&&this.options.autoSelect){if(this.options.allowBookmark&&location.href.indexOf('#')>-1){var sel=location.href.replace(/^.*#/,'');if(sel==name.id){this.selectPage(sel,false);}else{if(this.__initTimer){window.clearTimeout(this.__initTimer);}
this.__initTimer=window.setTimeout(this.__initialCheck.bind(this),500);}}else{this.selectPage(name.id,false);}}}
return name.id;}});